remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: ![Flautissimo logo](https://lynneflute.github.io/Flautissimo/logo.png)
description: The Southampton Flute Orchestra
